###### - Introduction to Pandas
###### - Series & DataFrame
###### - Creation of DataFrames, Exploring Data (Series and DataFrame)
###### - Operations on DataFrames

In [ ]:
import pandas as pd
import numpy as np

#### Series

##### - A one-dimensional array like structure along with indices as label.

In [ ]:
s1 = pd.Series([34, 67, 90, 34, 12, 67])
s2 = pd.Series(["sumit","rahul","meet"])
s1
s2

In [ ]:
print(s2[0])

In [ ]:
print(s1[0:3])

In [ ]:
print(s1[0::2])

#### DataFrame

##### - A multi-dimensional (2D) array like structure along with indices as label.

In [ ]:
df = pd.DataFrame()

print(df)

In [ ]:
df = pd.DataFrame({
    'name': ["vansh", "abhay", "dhruvi"],
    'age': [20, 18, 22],
    'marks': [80, 98, 94],
})

df

In [ ]:
df["name"]

In [ ]:
df[["name", "marks"]]

In [ ]:
df["name"][0]

In [ ]:
df[["name", "marks"]]

In [ ]:
df['marks']

In [ ]:
df

In [ ]:
df["city"] = ["delhi", "mumbai", "pune"]
df

In [ ]:
df["city"] = ["surat", "baroda", "ahmedabad"]
df

In [ ]:
print(df)

In [ ]:
df['marks'].dtypes

In [ ]:
df.dtypes

In [ ]:
type(df)

In [ ]:
type(s1)

In [ ]:
df['marks']

In [ ]:
df['marks'] + 2

In [ ]:
df['marks'] - 2

In [ ]:
df['marks'] * 2

In [ ]:
df['marks'] / 2

In [ ]:
df['marks'] % 2

In [ ]:
df

In [ ]:
df['marks'] = df['marks'] + 2

In [ ]:
df

In [ ]:
type(df['marks'])

In [ ]:
df2 = pd.DataFrame([
    ["aryan", "vansh", "dhruvi"],
    [20, 22, 18],
    [98, 78, 86]
])

df2

In [ ]:
df3 = pd.DataFrame([
    ["aryan", "vansh", "dhruvi"],
    [20, 22, 18],
    [98, 78, 86]
], index=["name", "age", "marks"])

df3

In [ ]:
df3 = pd.DataFrame([
    ["aryan", "vansh", "dhruvi"],
    [20, 22, 18],
    [98, 78, 86]
], columns=["name", "age", "marks"])

df3

In [ ]:
type(df3)

In [ ]:
type(df3['name'])

In [ ]:
# iloc & loc

In [36]:
lol = [
    ["Alice", 25, "New York"],
    ["Bob", 30, "London"],
    ["Charlie", 22, "Paris"]
]

df2 = pd.DataFrame(lol, columns=["Name", "Age", "City"])

df2

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris

In [37]:
df2["Name"]

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [38]:
df2.Name

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [39]:
df2.Name[0]

'Alice'

In [40]:
df2

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris

In [41]:
df2.iloc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [42]:
df2.iloc[0:2]

    Name  Age      City
0  Alice   25  New York
1    Bob   30    London

In [43]:
df2.iloc[0::2]

      Name  Age      City
0    Alice   25  New York
2  Charlie   22     Paris

In [44]:
df2.iloc[0:2, 0:2]

    Name  Age
0  Alice   25
1    Bob   30

In [45]:
df2.loc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [46]:
# How to set index from existing column

df3 = df2.set_index("Name")

In [47]:
df3

         Age      City
Name
Alice     25  New York
Bob       30    London
Charlie   22     Paris

In [48]:
df3.loc["Bob"]

Age         30
City    London
Name: Bob, dtype: object

In [49]:
df3.loc[["Alice", "Charlie"]]

         Age      City
Name
Alice     25  New York
Charlie   22     Paris

In [51]:
df3.loc["Alice":"Bob"]

       Age      City
Name
Alice   25  New York
Bob     30    London

In [52]:
df3.loc[df3["City"] != "London"]

         Age      City
Name
Alice     25  New York
Charlie   22     Paris