In [1]:
import pandas as pd

In [11]:
df = pd.DataFrame([
    ["ram",34,"rajkot"],
    ["shyam",24],
    ["meet",22,"amreli"],
])

df

       0   1       2
0    ram  34  rajkot
1  shyam  24    None
2   meet  22  amreli

In [12]:
df.isna().sum()

0    0
1    0
2    1
dtype: int64

In [9]:
df.dropna(axis=1,inplace=True)

In [ ]:
df.fillna("-",inplace=True)
df

       0   1       2
0    ram  34  rajkot
1  shyam  24       -
2   meet  22  amreli